Correct static cast in Streaming Arduino
Incorrect cast on `offset_usec` to 'long', given that it will only be
used in `struct timeval offset` as the `tv_usec` member, of type
'__darwin_suseconds_t' (aka 'int').

This build failed with the following error:
```
vrpn_Streaming_Arduino.C:217: error:
non-constant-expression cannot be narrowed from type 'long' to
'__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
```

This comes from the switch to C++11, the fix is to explicitly cast the
type (we know that long will still fit into int).